name: Release and Publish to NPM

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.2.3-beta, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # Required for npm provenance
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run security checks
        run: npm run security:check
        
      - name: Build project
        run: npm run build
        
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Update package.json version
        run: npm version ${{ steps.get_version.outputs.VERSION }} --no-git-tag-version
        
      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Changes in ${{ steps.get_version.outputs.VERSION }}
            
            ### 🔒 Security
            - ✅ Automated security scanning passed
            - ✅ No vulnerabilities detected in dependencies
            - ✅ No sensitive information found in codebase
            
            ### 📦 Package Info
            - Published to NPM: [`repomix-reader-mcp@${{ steps.get_version.outputs.VERSION }}`](https://www.npmjs.com/package/repomix-reader-mcp/v/${{ steps.get_version.outputs.VERSION }})
            - Build artifacts verified and tested
            
            ### 🚀 Installation
            ```bash
            npm install repomix-reader-mcp@${{ steps.get_version.outputs.VERSION }}
            ```
            
            View the [CHANGELOG](./README.md) for detailed changes.
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.VERSION, '-') }}
